//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by autorun.rc
//
#define IDD_AUTORUN_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDB_PLAY0                       131
#define IDB_PLAY1                       132
#define IDB_PLAY2                       133
#define IDB_BACK                        135
#define IDB_EXIT0                       139
#define IDB_EXIT1                       140
#define IDB_EXIT2                       141
#define IDB_UNINST0                     142
#define IDB_UNINST1                     143
#define IDB_UNINST2                     144
#define IDB_INST0                       145
#define IDB_INST1                       146
#define IDB_INST2                       147

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
